# Generated by Django 3.0.6 on 2020-05-28 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='country_of_birth',
        ),
    ]
