# Generated by Django 3.0.6 on 2020-05-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20200526_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='primary_nationality',
        ),
    ]
